# Konfiguracja WordPressa
wordpressUsername: user
wordpressPassword: "TwojeSilneHaslo123!"
wordpressEmail: user@example.com
wordpressFirstName: Jan
wordpressLastName: Kowalski
wordpressBlogName: "Moj Nowy Blog"

# Konfiguracja Bazy Danych
mariadb:
  enabled: true                          
  auth:
    rootPassword: "HasloDoBazy123!"
    username: bn_wordpress               
    password: "HasloUzytkownikaBazyDanych"
    database: bitnami_wordpress          
  primary:
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 10Gi                         

# Konfiguracja trwałości danych dla plików WordPressa
persistence:
  enabled: true
  storageClass: "longhorn"
  size: 10Gi

# Konfiguracja dostępu (Serwis typu LoadBalancer zamiast Ingressa dla uproszczenia klastra)
service:
  type: LoadBalancer

ingress:
  enabled: false
